[project]
name = "stockdata-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "finance-datareader>=0.9.96",
    "supabase>=2.20.0",
    "tqdm>=4.67.1",
]
